#########################################################################
#  _____  _                    _     _____              _               #
# /  __ \| |                  | |   | ___ \            | |              #
# | /  \/| |__   _   _  _ __  | | __| |_/ / _   _  ___ | |_  ___  _ __  #
# | |    |  _ \ | | | || '_ \ | |/ /| ___ \| | | |/ __|| __|/ _ \| '__| #
# | \__/\| | | || |_| || | | ||   < | |_/ /| |_| |\__ \| |_|  __/| |    #
#  \____/|_| |_| \__,_||_| |_||_|\_\\____/  \__,_||___/ \__|\___||_|    #
#                                                                       #
#########################################################################

chunkbuster:
  material: "ENDER_PORTAL_FRAME"
  glow: true

blocks-removed-per-tick: 600
can-place-in-wilderness: true
cooldown: 0
no-fall-seconds: 5
minimum-y: 0
maximum-y: 255

warmup:
  seconds: 0
  send-message-every-second: true
  warmup-sound-enabled: false
  warmup-sound: "random.levelup" # random.levelup is for 1.8 only
  warmup-sound-volume: 1.0
  warmup-sound-pitch: 1.0
  warmup-sound-interval: 1
  clearing-sound-enabled: false
  clearing-sound: "random.levelup"
  clearing-volume: 1.0
  clearing-pitch: 1.0

full-inv-drop-on-floor: false

confirm-gui:
  rows: 3
  confirm-material: "WOOL:5" # or GREEN_WOOL
  cancel-material: "WOOL:14" # or RED_WOOL
  fill-material: "AIR"
  title: "&7CONFIRMER CHUNK BUSTER"
  confirm-block-name: "&aCONFIRMER"
  cancel-block-name: "&cANNULER"
  fill-name: ""
  confirm-block-lore: [] # No lore
  cancel-block-lore: # One empty lore line
    - ""
  fill-lore: []
  confirm-sound-enabled: false
  confirm-sound: "random.levelup"
  confirm-volume: 1.0
  confirm-pitch: 1.0
  cancel-sound-enabled: false
  cancel-sound: "mob.villager.hit"
  cancel-volume: 1.0
  cancel-pitch: 1.0

messageschunk:
  give: "§6Anézia §f» §eTu as donné §6{amount} §echunkbuster(s) à §6{player}§e."
  receive: "§6Anézia §f» §eTu as reçu §6{amount} §echunkbuster(s)."
  no-permission-command: "§cVous n'avez pas la permission d'executer cette commande !"
  no-permission-place: "§6Anézia §f» §eTu ne peux pas placer de chunkbusters!"
  no-faction: "§6Anézia §f» §eTu dois avoir une faction pour poser un chunkbuster!"
  cannot-place: "§6Anézia §f» §eTu ne peux pas placer de chunkbusters ici ! Tu ne peux seulement en Wilderness ou sur tes territoires !"
  clearing-chunks: "§6Anézia §f» §eSupression du chunk !"
  clearing-in-seconds: "§6Anézia §f» §eLe chunk sera effacé dans §6{seconds} §eseconde(s)."
  not-minimum-role: "§6Anézia §f» §eTu dois être plus élevé dans cette faction pour pouvoir poser un chunkbuster."
  gui-cancel: "§6Anézia §f» §eLe chunkbuster a été annulé !"
  cooldown: "§6Anézia §f» §eTu dois attendre §6{minutes} §eminute(s) et §6{seconds} §eseconde(s) pour utiliser le chunkbuster !"
  no-item: "§6Anézia §f» §eTu dois avoir un chunkbuster dans ton inventaire !"

ignored-materials:
  - "BEDROCK"

hooks:
  factions: true # Check faction territories
  worldguard: true # Check for block-break flag in regions
  worldborder: true # Check for the worldborder, may or may not be a tiny bit slower

minimum-factions-role: "any"


############################################
#                                          #
#            Sell Wand Plugin              #
#                                          #
############################################

Messages:
  NoPermission: "§cVous n'avez pas la permission d'executer cette commande !"
  CorrectUsage: '§6Anézia §f» §eUsage correcte: /sellwand <player>'
  PlayerNotFound: "§6Anézia §f» §e%player% n'est pas en ligne."
  ItemReceived: '§6Anézia §f» §eTu viens de recevoir un bâton de vente.'
  ItemGiven: '§6Anézia §f» §eTu viens de donner un bâton de vente à %player%.'
  AmountAdded: '§6Anézia §f» §e$%amount% a bien été ajouté à ton compte.'
  Empty: '§6Anézia §f» §eCe coffre est actuellement vide.'
  Territory: "§6Anézia §f» §eTu ne peux pas l'utiliser sur le territoire d'une autre faction."

sellwand:
  type: STICK

items:
  263: 3
  331: 2
  351:4: 2,5
  265: 4
  266: 10
  264: 50
  388: 50
  115: 3,5
  39: 5
  296: 4
  360: 1,2
  391: 2,5
  81: 3
  338: 1,5



############################################
#                                          #
#          Unclaim Finder Plugin           #
#                                          #
############################################

durability: 25
use-message: "§6Anézia §f» §6%AMOUNT%&6% &ede chance de trouver une base. &6(%DURABILITY%/25)"
max-amount: 100

# -------------------------------
#     HLR v1.3.1 config file
# -------------------------------

# Choose which worlds the tweaked hopper will work in.
Enabled-in-worlds:
  - world

# Here you can choose what type of items the tweaked hopper will take in.
ItemList:
  # This includes all the common crops, i.e. Pumpkin, Cactus, Wheat, Seeds, Carrot,
  # Potato(including Poisonous ones), Sugarcane, Red/Brown Mushrooms, Melons and Nether warts.
  Crops: true
  # This includes all the common mob drops, i.e. Feather, Raw chicken, Raw Beef, Raw Porkchop,
  # Raw mutton, Spider eye, Ender pearl, Bone, Arrow, Wool, Iron Ingot, Blaze rod, Gunpowder,
  # String, Gold nugget, Slimeball, Ink sack, Leather, Rotten Flesh, Prismarine Shard, Prismarine Crystals and Raw Fish.
  Mob-drops: true
  # Here you can add the custom items you want to be taken in by the tweaked hopper.
  # Please use Bukkit's material list's name.
  # For those items with a damage value, please do the item name followed by a colon, as shown in example 2.
  Custom-items:
    # - EXAMPLE_MATERIAL
    # - EXAMPLE_MATERIAL:1
    -

      # Here you can set how many hoppers can be converted at once.
    # e.g. Max-amount: 5, players can't convert a stack of hoppers with more than 5 hoppers in it.
Max-amount: 10

# Use permissions?
Use-permissions: true

# You can set how many tweaked hoppers can be in 1 chunk here.
# set -1 for unlimited tweaked hoppers in one chunk.
# any number is or larger than 16*16 will be the same as unlimited tweaked hoppers.
Chunk-HopperLimit: -1

# Retain the tweaked hopper or drop a new hopper upon tweaked hopper breaking?
Retain-tweaked: false

# Here you can set if player drops would be picked up by the hopper or not.
Greedy-mode: false

# To further reduce lag caused by farms, this forces the following types of farms
# to only be able to work when a crop hopper is in the chunk.
# Set to false to disable the farm type.
Farm-tweaks:
  #This refers to the initial spawning of entities by spawners, not their death.
  Spawners:
    Allow: true
    #This allows specific types of spawners to still work under no crop hoppers.
    Whitelist:
      -
      #This refers to every farms using a piston to break the crop.
  Piston-farms:
    Allow: false
    #This blacklists the blocks you want pistons to not farm. Default is
    #Pumpkin, Melon and Sugarcane.
    Blacklist:
      - PUMPKIN
      - MELON_BLOCK
      - SUGAR_CANE_BLOCK
  #This refers to every farms using water to break the crop.
  Water-farms:
    Allow: true
    #This blacklists the blocks you want water to not flow and destroy. Default is
    #Potato, Carrot, Wheat and Nether warts.
    Blacklist:
      - POTATO
      - CARROT
      - CROPS
      - NETHER_WARTS
  #This refers to the conventional method of cactus breaking by adjacent block.
  Cactus-farms: true

# Enable /converthopper cooldown?
Cooldown:
  Enable: false
  Seconds: 30

# Use economy? Vault API required
Eco:
  Use: false
  Conversion-fee: 0.0


no-perm: "§cVous n'avez pas la permission d'executer cette commande !"
chest-warning: "§6Anézia §f» §eTu dois regarder le coffre !"
only-players: "§6Anézia §f» §eSeuls les joueurs peuvent exécuter cette commande !"
item-type-amount: "§6Anézia §f» §eContenue du coffre: §6%item%§e, nombre: §6%num%§e."
item-type: "§6Anézia §f» §eContenu du coffre: §e%item%!"
no-item: "§6Anézia §f» §eVous n'avez pas d'item spécial pour voir le contenu du coffre!"
mode-changed: "§6Anézia §f» §eLe mode d'affichage est devenu &e%state%."
reloaded: "§6Anézia §f» §eConfiguration rechargée!"
chest-name: "§eContenu coffre"

remove-item: false
show-amount: true
blacklisted-items:
  - STONE
  - SAND


auto-replant: true
allow-bonemeal-harvest: false
hooksa:
  WorldGuard: false
enabled-crops:
  carrot: true
  potato: true
  beetroot: true
  nether_wart: true
  wheat: true
  cocoa: true