#########################################################################
#  _____  _                    _     _____              _               #
# /  __ \| |                  | |   | ___ \            | |              #
# | /  \/| |__   _   _  _ __  | | __| |_/ / _   _  ___ | |_  ___  _ __  #
# | |    |  _ \ | | | || '_ \ | |/ /| ___ \| | | |/ __|| __|/ _ \| '__| #
# | \__/\| | | || |_| || | | ||   < | |_/ /| |_| |\__ \| |_|  __/| |    #
#  \____/|_| |_| \__,_||_| |_||_|\_\\____/  \__,_||___/ \__|\___||_|    #
#                                                                       #
#########################################################################

chunkbuster:
  material: "ENDER_PORTAL_FRAME" # or END_PORTAL_FRAME in 1.13+
  name: "&e\u2734 &a&lChunk Buster &e\u2734"
  lore:
    - "&7Radius: &e{area}"
    - ""
    - "&7Right click to place and destroy"
    - "&7all the blocks in your chunk radius."
  glow: true # Whether the item should glow as if it was enchanted.

# This amount of blocks will be processed from the queue per second
# High numbers will make the blocks disappear instantly, but especially with
# chunkbusters with 5+ radius, it may lag the server.
blocks-removed-per-tick: 600

# Change this to false if you don"t want to be able to destroy wilderness chunks. (factions)
can-place-in-wilderness: true

# The time you must wait before using another chunkbuster, in seconds. Set this to 0 for no cooldown.
cooldown: 0

# The amount of time that the player takes no fall damage after a chunk starts clearing. Set to 0 to disable.
no-fall-seconds: 5

# Chunkbusters clear between this minimum value and the maximum value (both inclusive). 0 and 255 means the whole chunk.
# You can use "{player}" for the player"s Y-coordinate.
minimum-y: 0
maximum-y: 255

warmup:
  # Wait this whole number of seconds before executing the chunkbuster.
  # This is useful if your players don"t have fly etc. 0 means no warmup.
  seconds: 0
  # If true, the "clearing-in-seconds" message will send every second, and then finally the "clearing-chunks" message.
  # If false, it will only say the first clearing message and then the "clearing-chunks" message.
  send-message-every-second: true
  warmup-sound-enabled: false
  # These are the sound names, not the ones from the bukkit enum. Make sure
  # to get the right names for your minecraft version (google search them).
  # This sound plays when the warmup starts.
  warmup-sound: "random.levelup" # random.levelup is for 1.8 only
  warmup-sound-volume: 1.0 # 0.0 to 1.0
  warmup-sound-pitch: 1.0 # 0.0 to 2.0 (ex. 0.5 is half sound speed, 1 is normal speed, 2 is double speed)
  # Choose the interval for the warmup sound, in seconds. 1 means the sound will play every second.
  warmup-sound-interval: 1
  # Sound played when the chunks start clearing. (After the warmup if it"s set)
  clearing-sound-enabled: false
  clearing-sound: "random.levelup"
  clearing-volume: 1.0
  clearing-pitch: 1.0

# Whether to drop the items on the floor if inventory is full.
full-inv-drop-on-floor: false

confirm-gui:
  # Maximum 6
  rows: 3
  confirm-material: "WOOL:5" # or GREEN_WOOL
  cancel-material: "WOOL:14" # or RED_WOOL
  fill-material: "AIR"
  # Please do not leave leave any of these below texts empty ("") please
  title: "&7CONFIRM CHUNK BUSTER"
  confirm-block-name: "&aCONFIRM"
  cancel-block-name: "&cDENY"
  fill-name: ""
  # The lores of the gui blocks. For no lore, put []. Otherwise
  # make it a list (-) like the chunkbuster lore.
  confirm-block-lore: [] # No lore
  cancel-block-lore: # One empty lore line
    - ""
  fill-lore: []
  # Sound when the confirm block is clicked
  confirm-sound-enabled: false
  confirm-sound: "random.levelup"
  confirm-volume: 1.0
  confirm-pitch: 1.0
  # Sound when the cancel block is clicked or chunk buster is not found in player's inventory
  cancel-sound-enabled: false
  cancel-sound: "mob.villager.hit"
  cancel-volume: 1.0
  cancel-pitch: 1.0

messages:
  give: "&aYou gave {player} {amount} chunkbuster(s)."
  receive: "&aYou have received {amount} chunkbuster(s)."
  no-permission-command: "&cNo permission!"
  no-permission-place: "&cYou cannot place chunkbusters!"
  no-faction: "&cYou must have a faction to use a chunk buster!"
  cannot-place: "&cYou cannot place chunk busters here! You can only place it in your territory or in wilderness!" # Change this to whatever makes sense
  clearing-chunks: "&aClearing the chunk(s)!"
  #This will only show if "chunkbuster-activation-delay" is above 0
  clearing-in-seconds: "&aChunk(s) will clear in {seconds} second(s)."
  not-minimum-role: "&cYou must be a faction (insert role) to use chunkbusters."
  gui-cancel: "&cThe chunkbuster has been cancelled."
  cooldown: "&cYou must wait {minutes} minute(s) and {seconds} second(s) to use this again!"
  no-item: "&cYou must have a chunk buster in your inventory!"

# Blocks that will not get cleared by chunkbusters. Use material enum names.
ignored-materials:
  - "BEDROCK"

hooks:
  factions: true # Check faction territories
  worldguard: true # Check for block-break flag in regions
  worldborder: true # Check for the worldborder, may or may not be a tiny bit slower

# The minimum factions role for using chunkbusters
# For FactionsUUID, set this to either "leader"/"admin", "coleader", "moderator", "member"/"normal", "recruit"/"any"
# For MassiveCore Factions, set this to either "leader"/"admin", "officer", "member"/"normal", "recruit"/"any"
minimum-factions-role: "any"



############################################
#******************************************#
#******************************************#
#****************BestHammer****************#
#******************1.0.2*******************#
#******************************************#
############################################

only-survival: false
hammer-name: "§cHammer"
lore: "§7- Can mine in a area of 3x3x2"

craft:
  etage0: "GGG"
  etage1: "GGG"
  etage2: " S "

key:
  - "G/GOLD_BLOCK/0"
  - "S/STICK/0"



############################################
#                                          #
#            Sell Wand Plugin              #
#                                          #
############################################

Messages:
  NoPermission: '&cYou do not have permission for this command.'
  CorrectUsage: '&cCorrect Usage: /sellwand <player>'
  PlayerNotFound: '&c%player% is not currently online.'
  ItemReceived: '&aYou have received a sell wand.'
  ItemGiven: '&aYou have given a sell wand to %player%.'
  AmountAdded: '&a$%amount% has been added to your account.'
  Empty: '&cThis chest is currently empty.'
  Territory: '&cYou cannot use this in another factions territory.'

sellwand:
  type: STICK
  name: '&a&lSell Wand'
  lore:
    - '&7Right-click on a chest to sell all the items inside.'

items: # Add a new itemstack id here
  264: 500 # This is the amount that will be added to the players account



############################################
#                                          #
#          Unclaim Finder Plugin           #
#                                          #
############################################

item:
  material: 347 # id or name
  data: '0'
  name: "&bUnclaimFinder &7(Clique droit)"
  lore: []
durability: 25
use-message: "&e%AMOUNT%&6% &fde chance de trouver une base. &c%DURABILITY%/25)"
max-amount: 100



main-config:
  hoe-name: "&aHarvestHoe"
  #The name of the harvestHoe (it shoud be the same to open the menu)
  hoe-lore:
    - "&7&m-------------&aHarvestHoe&7&m-------------"
    - ""
    - "&5*&bUse this hoe to harvest crops !"
    - "&bIt will automatically sell the harvested resources !"
    - ""
    - "&eTips:"
    - "&6- &dyou need a level to start harvesting !"
    - "&6- &dyou can use &c/hh safemode &dto only breaks ripe crops !"
    - "&6- &dsell prices depends of your harvest hoe level !"
    - ""
    - "&7&l(&eRight-Click to upgrade !&7&l)"
    - ""
    - "&7&m------------------------------"

  open-permission: "harvesthoe.open"
  #Here is the permission the player should have to open the menu
  requires-permission: false
  no-perm-message: "&cYou don't have the permission to open the harvest menu !"

  enable-open-menu-message: true
  #If true a message will be appears in the chat for the player

  open-menu-message: "&eOpening the menu..."
  #The message when a player open the menu

  open-sound:
    #The sound played when the player open the ml
    enabled: true
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 10
    pitch: 1

  safe-mode: #Safe mode give you the ability to not break crops when they are not mature
    enabled: true
    enable-message: "&7Safe mode &aEnabled !"
    disable-message: "&7Safe mode &cDisabled !"
    permission-require:
      enabled: true
      permission: "harvesthoe.safemode"

sounds:
  #For all the sounds, please use this list: https://helpch.at/docs/1.12.2/org/bukkit/Sound.html

  scane:
    enabled: true
    sound: BLOCK_NOTE_BELL
    volume: 10
    pitch: 1
  wheat:
    enabled: true
    sound: BLOCK_NOTE_BELL
    volume: 10
    pitch: 1
  carrots:
    enabled: true
    sound: BLOCK_NOTE_BELL
    volume: 10
    pitch: 1
  potatoes:
    enabled: true
    sound: BLOCK_NOTE_BELL
    volume: 10
    pitch: 1
  melons:
    enabled: true
    sound: BLOCK_NOTE_BELL
    volume: 10
    pitch: 1
  pumpkins:
    enabled: true
    sound: BLOCK_NOTE_BELL
    volume: 10
    pitch: 1
  netherwarts:
    enabled: true
    sound: BLOCK_NOTE_BELL
    volume: 10
    pitch: 1
  cocoabeans:
    enabled: true
    sound: BLOCK_NOTE_BELL
    volume: 10
    pitch: 1

gui:
  gui-name: "&a&lHarvest Hoe GUI"

  gui-size: 27
  #Can be 9, 18, 27, 36, 46, 54

  #For all the items, pleace use this list: https://helpch.at/docs/1.12.2/index.html?org/bukkit/Material.html

  levelone:
    title: "&b✪Level 1✪" #/!\ Don't put same title to each level up icons
    material: DOUBLE_PLANT
    data: 0
    levelup-sound:
      enabled: true
      sound: BLOCK_ANVIL_USE
      volume: 10
      pitch: 1
    lore:
      - "&c&m-----------------------"
      - ""
      - "&e&lPrices:"
      - ""
      - "&6- &bSugar-Cane&6: &a25$"
      - "&6- &bWheat&6: &a30$"
      - "&6- &bCarrots&6: &a30$"
      - "&6- &bPotatoes&6: &a30$"
      - "&6- &bMelons&6: &a30$"
      - "&6- &bPumpkins&6: &a30$"
      - "&6- &bCocoabeans&6: &a35$"
      - "&6- &bNetherWarts&6: &a40$"
      - ""
      - "&7Price to unlock: &c25000$"
      - "&7Status: &c✘"
      - ""
      - "&c&m-----------------------"
    unlocked-lore:
      - "&a&m-----------------------"
      - ""
      - "&e&lPrices:"
      - ""
      - "&6- &bSugar-Cane&6: &a25$"
      - "&6- &bWheat&6: &a30$"
      - "&6- &bCarrots&6: &a30$"
      - "&6- &bPotatoes&6: &a30$"
      - "&6- &bMelons&6: &a30$"
      - "&6- &bPumpkins&6: &a30$"
      - "&6- &bCocoabeans&6: &a35$"
      - "&6- &bNetherWarts&6: &a40$"
      - ""
      - "&7Status: &a✔"
      - ""
      - "&a&m-----------------------"
    #To write on a new line, put ";;" symbol
    slot: 11
    quantity: 1
    permission-to-access: "harvesthoe.levelone"
    #Here is the permission that makes the player able to upgrade his harvesthoe to level one !
    permission-to-get-unlocked: "harvesthoe.levelone.unlocked"
    #Here is the permission to unlock to level for a player, if you want to upgrade harvesthoe to level one for a player
    #just add him this permission (and remove other "permission-to-get-unlocked" from other levels to the player)
    #Example:
    #if you want a player to get level 3 unlocked, remove the permissions: "harvesthoe.levelone.unlocked" and "harvesthoe.leveltwo.unlocked" (if he have thoses)
    #and now you can add "harvesthoe.levelthree.unlocked" to him !
    price-to-upgrade: 25000
    scane:
      enabled: true
      sell-price: 25
    wheat:
      enabled: true
      sell-price: 30
    carrots:
      enabled: true
      sell-price: 30
    potatoes:
      enabled: true
      sell-price: 30
    melons:
      enabled: true
      sell-price: 30
    pumpkins:
      enabled: true
      sell-price: 30
    netherwarts:
      enabled: true
      sell-price: 40
    cocoabeans:
      enabled: true
      sell-price: 35

  leveltwo:
    title: "&b✪✪Level 2✪✪" #/!\ Don't put same title to each level up icons
    material: DOUBLE_PLANT
    data: 0
    levelup-sound:
      enabled: true
      sound: BLOCK_ANVIL_USE
      volume: 10
      pitch: 1
    lore:
      - "&c&m-----------------------"
      - ""
      - "&e&lPrices:"
      - ""
      - "&6- &bSugar-Cane&6: &a30$"
      - "&6- &bWheat&6: &a35$"
      - "&6- &bCarrots&6: &a35$"
      - "&6- &bPotatoes&6: &a35$"
      - "&6- &bMelons&6: &a35$"
      - "&6- &bPumpkins&6: &a35$"
      - "&6- &bCocoabeans&6: &a40$"
      - "&6- &bNetherWarts&6: &a45$"
      - ""
      - "&7Price to unlock: &c25000$"
      - "&7Status: &c✘"
      - ""
      - "&c&m-----------------------"
    unlocked-lore:
      - "&a&m-----------------------"
      - ""
      - "&e&lPrices:"
      - ""
      - "&6- &bSugar-Cane&6: &a30$"
      - "&6- &bWheat&6: &a35$"
      - "&6- &bCarrots&6: &a35$"
      - "&6- &bPotatoes&6: &a35$"
      - "&6- &bMelons&6: &a35$"
      - "&6- &bPumpkins&6: &a35$"
      - "&6- &bCocoabeans&6: &a40$"
      - "&6- &bNetherWarts&6: &a45$"
      - ""
      - "&7Status: &a✔"
      - ""
      - "&a&m-----------------------"
    #To write on a new line, put ";;" symbol
    slot: 13
    quantity: 2
    permission-to-access: "harvesthoe.leveltwo"
    #Here is the permission that makes the player able to upgrade his harvesthoe to level two !
    permission-to-get-unlocked: "harvesthoe.leveltwo.unlocked"
    #Here is the permission to unlock to level for a player, if you want to upgrade harvesthoe to level two for a player
    #just add him this permission (and remove other "permission-to-get-unlocked" from other levels to the player)
    #Example:
    #if you want a player to get level 3 unlocked, remove the permissions: "harvesthoe.levelone.unlocked" and "harvesthoe.leveltwo.unlocked" (if he have thoses)
    #and now you can add "harvesthoe.levelthree.unlocked" to him !
    price-to-upgrade: 75000
    scane:
      enabled: true
      sell-price: 30
    wheat:
      enabled: true
      sell-price: 35
    carrots:
      enabled: true
      sell-price: 35
    potatoes:
      enabled: true
      sell-price: 35
    melons:
      enabled: true
      sell-price: 35
    pumpkins:
      enabled: true
      sell-price: 35
    netherwarts:
      enabled: true
      sell-price: 45
    cocoabeans:
      enabled: true
      sell-price: 40

  levelthree:
    title: "&b✪✪✪Level 3✪✪✪" #/!\ Don't put same title to each level up icons
    material: DOUBLE_PLANT
    data: 0
    levelup-sound:
      enabled: true
      sound: BLOCK_ANVIL_USE
      volume: 10
      pitch: 1
    lore:
      - "&c&m-----------------------"
      - ""
      - "&e&lPrices:"
      - ""
      - "&6- &bSugar-Cane&6: &a35$"
      - "&6- &bWheat&6: &a40$"
      - "&6- &bCarrots&6: &a40$"
      - "&6- &bPotatoes&6: &a30$"
      - "&6- &bMelons&6: &a40$"
      - "&6- &bPumpkins&6: &a40$"
      - "&6- &bCocoabeans&6: &a45$"
      - "&6- &bNetherWarts&6: &a50$"
      - ""
      - "&7Price to unlock: &c25000$"
      - "&7Status: &c✘"
      - ""
      - "&c&m-----------------------"
    unlocked-lore:
      - "&a&m-----------------------"
      - ""
      - "&e&lPrices:"
      - ""
      - "&6- &bSugar-Cane&6: &a35$"
      - "&6- &bWheat&6: &a40$"
      - "&6- &bCarrots&6: &a40$"
      - "&6- &bPotatoes&6: &a30$"
      - "&6- &bMelons&6: &a40$"
      - "&6- &bPumpkins&6: &a40$"
      - "&6- &bCocoabeans&6: &a45$"
      - "&6- &bNetherWarts&6: &a50$"
      - ""
      - "&7Status: &a✔"
      - ""
      - "&a&m-----------------------"
    #To write on a new line, put ";;" symbol
    slot: 15
    quantity: 3
    permission-to-access: "harvesthoe.levelthree"
    #Here is the permission that makes the player able to upgrade his harvesthoe to level three !
    permission-to-get-unlocked: "harvesthoe.levelthree.unlocked"
    #Here is the permission to unlock to level for a player, if you want to upgrade harvesthoe to level three for a player
    #just add him this permission (and remove other "permission-to-get-unlocked" from other levels to the player)
    #Example:
    #if you want a player to get level 3 unlocked, remove the permissions: "harvesthoe.levelone.unlocked" and "harvesthoe.leveltwo.unlocked" (if he have thoses)
    #and now you can add "harvesthoe.levelthree.unlocked" to him !
    price-to-upgrade: 250000
    scane:
      enabled: true
      sell-price: 35
    wheat:
      enabled: true
      sell-price: 40
    carrots:
      enabled: true
      sell-price: 40
    potatoes:
      enabled: true
      sell-price: 40
    melons:
      enabled: true
      sell-price: 40
    pumpkins:
      enabled: true
      sell-price: 40
    netherwarts:
      enabled: true
      sell-price: 50
    cocoabeans:
      enabled: true
      sell-price: 45

  quit:
    title: "&cQuit"
    material: REDSTONE_BLOCK
    data: 0
    lore:
      - "&cClose this GUI"
      - ""
      - "&7(Left-Click)"
    #To write on a new line, put ";;" symbol
    slot: 26

  other: #Use this to fill empty spaces if u want
    title: " "
    material: STAINED_GLASS_PANE
    data: 3
    #Put 0 to data if u don't want to use it
    lore:
      - ""
    #To write on a new line, put ";;" symbol
    slots: "0,1,2,3,4,5,6,7,8,9,17,18,19,20,21,22,23,24,25"
    #To put multiple slots, please use ","

auto-replant: #Auto Replant gives you the ability to auto replant crops after breaking
  wheat: true
  carrots: true
  potatoes: true
  netherwarts: true
  cocoabeans: true

messages:
  prefix-sell-messages: "&7[&aHarvestHoe&7] "

  #Placeholders you can use:
  # - %quantity% --> Return the amount of items selled
  # - %price%    --> Return the money earned by the player
  # - %player%   --> Return the nickname of the player

  scane:
    chat:
      enabled: true
      message: "&a+%quantity% SugarCanes selled ! (&7+ %price%$&a)"
    hotbar:
      enabled: true
      message: "&a+%quantity% SugarCanes selled ! (&7+ %price%$&a)"

  wheat:
    chat:
      enabled: true
      message: "&a+%quantity% Wheat selled ! (&7+ %price%$&a)"
    hotbar:
      enabled: true
      message: "&a+%quantity% Wheat selled ! (&7+ %price%$&a)"

  carrots:
    chat:
      enabled: true
      message: "&a+%quantity% Carrots selled ! (&7+ %price%$&a)"
    hotbar:
      enabled: true
      message: "&a+%quantity% Carrots selled ! (&7+ %price%$&a)"

  potatoes:
    chat:
      enabled: true
      message: "&a+%quantity% Potatoes selled ! (&7+ %price%$&a)"
    hotbar:
      enabled: true
      message: "&a+%quantity% Potatoes selled ! (&7+ %price%$&a)"

  melons:
    chat:
      enabled: true
      message: "&a+%quantity% Melons selled ! (&7+ %price%$&a)"
    hotbar:
      enabled: true
      message: "&a+%quantity% Melons selled ! (&7+ %price%$&a)"

  pumpkins:
    chat:
      enabled: true
      message: "&a+%quantity% Pumpkins selled ! (&7+ %price%$&a)"
    hotbar:
      enabled: true
      message: "&a+%quantity% Pumpkins selled ! (&7+ %price%$&a)"

  netherwarts:
    chat:
      enabled: true
      message: "&a+%quantity% NetherWarts selled ! (&7+ %price%$&a)"
    hotbar:
      enabled: true
      message: "&a+%quantity% NetherWarts selled ! (&7+ %price%$&a)"

  cocoabeans:
    chat:
      enabled: true
      message: "&a+%quantity% CocoaBeans selled ! (&7+ %price%$&a)"
    hotbar:
      enabled: true
      message: "&a+%quantity% CocoaBeans selled ! (&7+ %price%$&a)"