#########################################################################
#  _____  _                    _     _____              _               #
# /  __ \| |                  | |   | ___ \            | |              #
# | /  \/| |__   _   _  _ __  | | __| |_/ / _   _  ___ | |_  ___  _ __  #
# | |    |  _ \ | | | || '_ \ | |/ /| ___ \| | | |/ __|| __|/ _ \| '__| #
# | \__/\| | | || |_| || | | ||   < | |_/ /| |_| |\__ \| |_|  __/| |    #
#  \____/|_| |_| \__,_||_| |_||_|\_\\____/  \__,_||___/ \__|\___||_|    #
#                                                                       #
#########################################################################

chunkbuster:
  material: "ENDER_PORTAL_FRAME" # or END_PORTAL_FRAME in 1.13+
  name: "&e\u2734 &a&lChunk Buster &e\u2734"
  lore:
    - "&7Radius: &e{area}"
    - ""
    - "&7Right click to place and destroy"
    - "&7all the blocks in your chunk radius."
  glow: true # Whether the item should glow as if it was enchanted.

# This amount of blocks will be processed from the queue per second
# High numbers will make the blocks disappear instantly, but especially with
# chunkbusters with 5+ radius, it may lag the server.
blocks-removed-per-tick: 600

# Change this to false if you don"t want to be able to destroy wilderness chunks. (factions)
can-place-in-wilderness: true

# The time you must wait before using another chunkbuster, in seconds. Set this to 0 for no cooldown.
cooldown: 0

# The amount of time that the player takes no fall damage after a chunk starts clearing. Set to 0 to disable.
no-fall-seconds: 5

# Chunkbusters clear between this minimum value and the maximum value (both inclusive). 0 and 255 means the whole chunk.
# You can use "{player}" for the player"s Y-coordinate.
minimum-y: 0
maximum-y: 255

warmup:
  # Wait this whole number of seconds before executing the chunkbuster.
  # This is useful if your players don"t have fly etc. 0 means no warmup.
  seconds: 0
  # If true, the "clearing-in-seconds" message will send every second, and then finally the "clearing-chunks" message.
  # If false, it will only say the first clearing message and then the "clearing-chunks" message.
  send-message-every-second: true
  warmup-sound-enabled: false
  # These are the sound names, not the ones from the bukkit enum. Make sure
  # to get the right names for your minecraft version (google search them).
  # This sound plays when the warmup starts.
  warmup-sound: "random.levelup" # random.levelup is for 1.8 only
  warmup-sound-volume: 1.0 # 0.0 to 1.0
  warmup-sound-pitch: 1.0 # 0.0 to 2.0 (ex. 0.5 is half sound speed, 1 is normal speed, 2 is double speed)
  # Choose the interval for the warmup sound, in seconds. 1 means the sound will play every second.
  warmup-sound-interval: 1
  # Sound played when the chunks start clearing. (After the warmup if it"s set)
  clearing-sound-enabled: false
  clearing-sound: "random.levelup"
  clearing-volume: 1.0
  clearing-pitch: 1.0

# Whether to drop the items on the floor if inventory is full.
full-inv-drop-on-floor: false

confirm-gui:
  # Maximum 6
  rows: 3
  confirm-material: "WOOL:5" # or GREEN_WOOL
  cancel-material: "WOOL:14" # or RED_WOOL
  fill-material: "AIR"
  # Please do not leave leave any of these below texts empty ("") please
  title: "&7CONFIRM CHUNK BUSTER"
  confirm-block-name: "&aCONFIRM"
  cancel-block-name: "&cDENY"
  fill-name: ""
  # The lores of the gui blocks. For no lore, put []. Otherwise
  # make it a list (-) like the chunkbuster lore.
  confirm-block-lore: [] # No lore
  cancel-block-lore: # One empty lore line
    - ""
  fill-lore: []
  # Sound when the confirm block is clicked
  confirm-sound-enabled: false
  confirm-sound: "random.levelup"
  confirm-volume: 1.0
  confirm-pitch: 1.0
  # Sound when the cancel block is clicked or chunk buster is not found in player's inventory
  cancel-sound-enabled: false
  cancel-sound: "mob.villager.hit"
  cancel-volume: 1.0
  cancel-pitch: 1.0

messages:
  give: "&aYou gave {player} {amount} chunkbuster(s)."
  receive: "&aYou have received {amount} chunkbuster(s)."
  no-permission-command: "&cNo permission!"
  no-permission-place: "&cYou cannot place chunkbusters!"
  no-faction: "&cYou must have a faction to use a chunk buster!"
  cannot-place: "&cYou cannot place chunk busters here! You can only place it in your territory or in wilderness!" # Change this to whatever makes sense
  clearing-chunks: "&aClearing the chunk(s)!"
  #This will only show if "chunkbuster-activation-delay" is above 0
  clearing-in-seconds: "&aChunk(s) will clear in {seconds} second(s)."
  not-minimum-role: "&cYou must be a faction (insert role) to use chunkbusters."
  gui-cancel: "&cThe chunkbuster has been cancelled."
  cooldown: "&cYou must wait {minutes} minute(s) and {seconds} second(s) to use this again!"
  no-item: "&cYou must have a chunk buster in your inventory!"

# Blocks that will not get cleared by chunkbusters. Use material enum names.
ignored-materials:
  - "BEDROCK"

hooks:
  factions: true # Check faction territories
  worldguard: true # Check for block-break flag in regions
  worldborder: true # Check for the worldborder, may or may not be a tiny bit slower

# The minimum factions role for using chunkbusters
# For FactionsUUID, set this to either "leader"/"admin", "coleader", "moderator", "member"/"normal", "recruit"/"any"
# For MassiveCore Factions, set this to either "leader"/"admin", "officer", "member"/"normal", "recruit"/"any"
minimum-factions-role: "any"



############################################
#******************************************#
#******************************************#
#****************BestHammer****************#
#******************1.0.2*******************#
#******************************************#
############################################

only-survival: false
hammer-name: "§cHammer"
lore: "§7- Can mine in a area of 3x3x2"

craft:
  etage0: "GGG"
  etage1: "GGG"
  etage2: " S "

key:
  - "G/GOLD_BLOCK/0"
  - "S/STICK/0"



############################################
#                                          #
#            Sell Wand Plugin              #
#                                          #
############################################

Messages:
  NoPermission: '&cYou do not have permission for this command.'
  CorrectUsage: '&cCorrect Usage: /sellwand <player>'
  PlayerNotFound: '&c%player% is not currently online.'
  ItemReceived: '&aYou have received a sell wand.'
  ItemGiven: '&aYou have given a sell wand to %player%.'
  AmountAdded: '&a$%amount% has been added to your account.'
  Empty: '&cThis chest is currently empty.'
  Territory: '&cYou cannot use this in another factions territory.'

sellwand:
  type: STICK
  name: '&a&lSell Wand'
  lore:
    - '&7Right-click on a chest to sell all the items inside.'

items: # Add a new itemstack id here
  264: 500 # This is the amount that will be added to the players account



############################################
#                                          #
#          Unclaim Finder Plugin           #
#                                          #
############################################

item:
  material: 347 # id or name
  data: '0'
  name: "&bUnclaimFinder &7(Clique droit)"
  lore: []
durability: 25
use-message: "&e%AMOUNT%&6% &fde chance de trouver une base. &c%DURABILITY%/25)"
max-amount: 100